stages:
  - build
  - code_style
  - integration_tests
  - deploy

build_simplebashutils:
  stage: build
  tags:
    - tag1
  script:
    - git clone ssh://git@git-ssh.21-school.ru:2222/students/C3_SimpleBashUtils.ID_353513/maudeluc/C3_SimpleBashUtils-1.git -b develop cloned_repo
    - cd cloned_repo/src/cat && make
    - cd ../grep && make
  artifacts:
    paths:
      - cloned_repo/src/cat/s21_cat
      - cloned_repo/src/grep/s21_grep
    expire_in: 30 days

check_code_style:
  stage: code_style
  tags:
    - tag1
  needs:
    - job: build_simplebashutils
      artifacts: true
  script:
    - apt-get update && apt-get install -y clang-format
    - cd cloned_repo
    - echo "Running clang-format check..."
    - >
      find . -name "*.[ch]" -exec clang-format -n --verbose {} + 
      || (echo "❌ Code style check failed!" && exit 1)

integration_tests:
  stage: integration_tests
  tags:
    - tag1
  needs:
    - job: build_simplebashutils
      artifacts: true
    - job: check_code_style
      artifacts: false
  script:
    - git clone ssh://git@git-ssh.21-school.ru:2222/students/C3_SimpleBashUtils.ID_353513/maudeluc/C3_SimpleBashUtils-1.git -b develop cloned_repo_tests
    - cp cloned_repo/src/cat/s21_cat cloned_repo_tests/src/cat/
    - cp cloned_repo/src/grep/s21_grep cloned_repo_tests/src/grep/
    - cd cloned_repo_tests/src/cat
    - echo "Running cat integration tests..."
    - bash tests.sh #| grep -m 1 Fail && exit 1

deployment:
  stage: deploy
  tags:
    - tag1
  needs:
    - job: build_simplebashutils
      artifacts: true
    - job: check_code_style
      artifacts: false
    - job: integration_tests
      artifacts: false
  script:
    - scp cloned_repo/src/cat/s21_cat maudeluc@192.168.31.232:
    - scp cloned_repo/src/grep/s21_grep maudeluc@192.168.31.232:
    - ssh -t maudeluc@192.168.31.232 'sudo mv s21_cat /usr/local/bin'
    - echo "1234\n"
    - ssh -t maudeluc@192.168.31.232 'sudo mv s21_grep /usr/local/bin'
    - echo "1234\n"
